import json
import os
import time
import yfinance as yf

OUTPUT_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data', 'yahoo_live_companies.json')

candidates = [
    ("Abbott India", "ABBOTINDIA.NS", "Healthcare"),
    ("Adani Enterprises", "ADANIENT.NS", "Infrastructure"),
    ("Adani Ports", "ADANIPORTS.NS", "Ports"),
    ("Adani Power", "ADANIPOWER.NS", "Power"),
    ("Adani Total Gas", "ADANIGAS.NS", "Gas"),
    ("Adani Green Energy", "ADANIGREEN.NS", "Energy"),
    ("Aarti Industries", "AARTIIND.NS", "Chemicals"),
    ("ABB India", "ABB.NS", "Industrial"),
    ("Aditya Birla Fashion", "ABFRL.NS", "Retail"),
    ("Ajanta Pharma", "AJANTPHARM.NS", "Pharma"),
    ("Akzo Nobel India", "AKZOINDIA.NS", "Chemicals"),
    ("Alicon Castalloy", "ALICON.NS", "Manufacturing"),
    ("Alkem Laboratories", "ALKEM.NS", "Pharma"),
    ("Allcargo Logistics", "ALLCARGO.NS", "Logistics"),
    ("Alstom India", "ALSTOMT&D.NS", "Engineering"),
    ("Amara Raja Batteries", "AMARAJABAT.NS", "Automobile"),
    ("Apar Industries", "APARINDS.NS", "Chemicals"),
    ("Arvind Limited", "ARVIND.NS", "Textiles"),
    ("Ashiana Housing", "ASHIANA.NS", "Real Estate"),
    ("Astrazeneca Pharma", "ASTRAZENCA.NS", "Pharma"),
    ("Atul Limited", "ATUL.NS", "Chemicals"),
    ("Aurobindo Pharma", "AUROPHARMA.NS", "Pharma"),
    ("BASF India", "BASF.NS", "Chemicals"),
    ("BEML Limited", "BEML.NS", "Engineering"),
    ("Bharat Dynamics", "BDL.NS", "Defense"),
    ("Bharat Electronics", "BEL.NS", "Defense"),
    ("Bharat Forge", "BHARATFORG.NS", "Auto Components"),
    ("Bharat Heavy Electricals", "BHEL.NS", "Engineering"),
    ("Bharat Rasayan", "BHARATRAS.NS", "Chemicals"),
    ("Bikaji Foods", "BIKAJIFIN.NS", "Food"),
    ("Blue Star", "BLUESTARCO.NS", "Consumer Durables"),
    ("Bombay Burmah Trading", "BBTC.NS", "Plantations"),
    ("Can Fin Homes", "CANFINHOME.NS", "Finance"),
    ("Caplin Point Laboratories", "CAPLIPOINT.NS", "Pharma"),
    ("Carborundum Universal", "CARBORUNIV.NS", "Materials"),
    ("Century Textiles", "CENTURYTEX.NS", "Textiles"),
    ("Chambal Fertilizers", "CHAMBLFERT.NS", "Fertilizers"),
    ("Chennai Petrochem", "CHENNPETRO.NS", "Energy"),
    ("Cochin Shipyard", "COCHINSHIP.NS", "Shipbuilding"),
    ("Crompton Greaves", "CROMPTON.NS", "Consumer Durables"),
    ("Cummins India", "CUMMINSIND.NS", "Engineering"),
    ("Dalmia Bharat", "DALBHARAT.NS", "Cement"),
    ("Delta Corp", "DELTACORP.NS", "Gaming"),
    ("Dish TV", "DISHTV.NS", "Media"),
    ("DLF Limited", "DLF.NS", "Real Estate"),
    ("Edelweiss Financial", "EDELWEISS.NS", "Finance"),
    ("Elgi Equipments", "ELGIEQUIP.NS", "Engineering"),
    ("Endurance Technologies", "ENDURANCE.NS", "Auto Components"),
    ("Engineers India", "ENGINERSIND.NS", "Engineering"),
    ("Equitas Small Finance Bank", "EQUITASBNK.NS", "Banking"),
    ("Eris Lifesciences", "ERIS.NS", "Pharma"),
    ("Escorts Kubota", "ESCORTS.NS", "Engineering"),
    ("FDC Limited", "FDC.NS", "Pharma"),
    ("Finolex Industries", "FINOLEXIND.NS", "Cables"),
    ("Firstsource Solutions", "FSL.NS", "IT"),
    ("Ganesha Ecosphere", "GANESHHOUC.NS", "Plastics"),
    ("Garden Reach Shipbuilders", "GRSE.NS", "Defense"),
    ("Glenmark Pharma", "GLENMARK.NS", "Pharma"),
    ("Global Health", "GLOBALHEALTH.NS", "Healthcare"),
    ("Godfrey Phillips", "GODFRYPHLP.NS", "Tobacco"),
    ("Gokaldas Exports", "GOKEX.NS", "Textiles"),
    ("Gopal Snacks", "GOPALKRISH.NS", "Food"),
    ("Granules India", "GRANULES.NS", "Pharma"),
    ("HFCL Limited", "HFCL.NS", "Telecom"),
    ("Himadri Speciality", "HSCL.NS", "Chemicals"),
    ("Indiamart Intermesh", "INDIAMART.NS", "E-commerce"),
    ("Indian Renewable Energy", "IREDA.NS", "Energy"),
    ("Indoco Remedies", "INDOCORE.NS", "Pharma"),
    ("Jindal Saw", "JINDALSAW.NS", "Steel"),
    ("Jio Platforms", "JIOPLATFORMS.NS", "Telecom"),
    ("KEI Industries", "KEI.NS", "Electrical"),
    ("KFin Technologies", "KFINTECH.NS", "Finance"),
    ("KPR Mill", "KPRMILL.NS", "Textiles"),
    ("LaOpala", "LAOPALA.NS", "Consumer Goods"),
    ("L&T Technology Services", "LTTS.NS", "IT"),
    ("Mahindra Holidays", "MHRIL.NS", "Hospitality"),
    ("Mahindra Lifespace", "MAHLIFE.NS", "Real Estate"),
    ("Manappuram Finance", "MANAPPURAM.NS", "Finance"),
    ("Metropolis Healthcare", "METROPOLIS.NS", "Healthcare"),
    ("Minda Corporation", "MINDAIND.NS", "Auto Components"),
    ("Mold-Tek Packaging", "MOLDTECH.NS", "Packaging"),
    ("Narayana Hrudayalaya", "NH.NS", "Healthcare"),
    ("NLC India", "NLCINDIA.NS", "Energy"),
    ("Oberoi Realty", "OBEROIREALTY.NS", "Real Estate"),
    ("One 97 Communications", "PAYTM.NS", "Fintech"),
    ("PB Fintech", "PBFI.NS", "Finance"),
    ("Patanjali Foods", "PATANJALI.NS", "Food"),
    ("Piramal Pharma", "PPLPHARMA.NS", "Pharma"),
    ("Poonawalla Fincorp", "POONAWALLA.NS", "Finance"),
    ("Prataap Snacks", "PRATAPSNACKS.NS", "Food"),
    ("RBL Bank", "RBLBANK.NS", "Banking"),
    ("Relaxo Footwears", "RELAXO.NS", "Consumer Goods"),
    ("RITES Limited", "RITES.NS", "Engineering"),
    ("Rossari Biotech", "ROSSARI.NS", "Chemicals"),
    ("SBI Life", "SBILIFE.NS", "Insurance"),
    ("Schaeffler India", "SCHAEFFLER.NS", "Engineering"),
    ("Sharda Cropchem", "SHARDACROP.NS", "Agrochemicals"),
    ("Shoppers Stop", "SHOPERSTOP.NS", "Retail"),
    ("Solar Industries", "SOLARINDS.NS", "Defense"),
    ("SpiceJet", "SPICEJET.NS", "Aviation"),
    ("Star Health", "STARHEALTH.NS", "Insurance"),
    ("Sundaram Finance", "SUNDARMFIN.NS", "Finance"),
    ("Sundram Fasteners", "SUNDRMFAST.NS", "Auto Components"),
    ("Suprajit Engineering", "SUPRAJIT.NS", "Auto Components"),
    ("Tata Communications", "TATACOMM.NS", "Telecom"),
    ("Tata Investment Corporation", "TATAINVEST.NS", "Finance"),
    ("Tata Power", "TATAPOWER.NS", "Energy"),
    ("Tata Teleservices", "TTML.NS", "Telecom"),
    ("Tejas Networks", "TEJASNET.NS", "Telecom"),
    ("The Phoenix Mills", "PHOENIXLTD.NS", "Real Estate"),
    ("Timken India", "TIMKEN.NS", "Engineering"),
    ("Trent Limited", "TRENT.NS", "Retail"),
    ("Tube Investments", "TIINDIA.NS", "Engineering"),
    ("United Spirits", "UNITEDSPIRITS.NS", "Beverages"),
    ("V-Guard Industries", "VGUARD.NS", "Consumer Durables"),
    ("Varun Beverages", "VARUNBEVERAGES.NS", "Food"),
    ("Vijaya Diagnostics", "VIJAYAHR.NS", "Healthcare"),
    ("Vipul Limited", "VIPULLTD.NS", "Real Estate"),
    ("Wockhardt", "WOCKPHARMA.NS", "Pharma"),
    ("Yes Bank", "YESBANK.NS", "Banking"),
    ("Zensar Technologies", "ZENSARTECH.NS", "IT"),
    ("Zota Health", "ZOTA.NS", "Healthcare"),
    ("Happiest Minds", "HAPPSTMNDS.NS", "IT"),
    ("Laurus Labs", "LAURUSLABS.NS", "Pharma"),
    ("Mankind Pharma", "MANKIND.NS", "Pharma"),
    ("Persistent Systems", "PERSISTENT.NS", "IT"),
    ("KPIT Technologies", "KPITTECH.NS", "IT"),
    ("Coforge", "COFORGE.NS", "IT"),
    ("Mphasis", "MPHASIS.NS", "IT"),
    ("AIA Engineering", "AIAENG.NS", "Engineering"),
    ("NCC Limited", "NCC.NS", "Infrastructure"),
    ("Mahanagar Gas", "MGL.NS", "Gas"),
    ("Gujarat State Petronet", "GSPL.NS", "Energy"),
    ("Jindal Stainless", "JSL.NS", "Steel"),
    ("UCO Bank", "UCOBANK.NS", "Banking"),
    ("GMR Airports", "GMRAIRPORTS.NS", "Infrastructure"),
    ("Vedanta Limited", "VEDL.NS", "Mining"),
    ("NMDC Limited", "NMDC.NS", "Mining"),
    ("BSE Limited", "BSE.NS", "Financial Services"),
    ("Jio Financial Services", "JIOFIN.NS", "Finance"),
    ("Aster DM Healthcare", "ASTERDM.NS", "Healthcare"),
    ("Fortis Healthcare", "FORTIS.NS", "Healthcare"),
    ("Max Healthcare", "MAXHEALTH.NS", "Healthcare"),
    ("Lemon Tree Hotels", "LEMONTREE.NS", "Hospitality"),
    ("Piramal Enterprises", "PIRAMAL.NS", "Finance"),
    ("Navin Fluorine International", "NAVINFLUOR.NS", "Chemicals"),
    ("Aegis Logistics", "AEGISLOG.NS", "Logistics"),
    ("Prince Pipes and Fittings", "PRINCEPIPE.NS", "Plastics"),
    ("Sona BLW Precision Forgings", "SONABLW.NS", "Auto Components"),
    ("Sapphire Foods", "SAPPHIRE.NS", "Food"),
    ("Narayana Hrudayalaya", "NH.NS", "Healthcare"),
    ("Jubilant Pharmova", "JUBLPHARMA.NS", "Pharma"),
    ("Bikaji Foods", "BIKAJIFIN.NS", "Food"),
    ("Polycab India", "POLYCAB.NS", "Electrical"),
    ("Angel One", "ANGELONE.NS", "Finance"),
    ("Dixon Technologies", "DIXON.NS", "Electronics"),
    ("Bharat Electronics", "BEL.NS", "Defense"),
    ("Mahanagar Gas", "MGL.NS", "Gas"),
    ("Gujarat State Petronet", "GSPL.NS", "Energy"),
    ("Jindal Stainless", "JSL.NS", "Steel"),
    ("Tata Chemicals", "TATACHEM.NS", "Chemicals"),
    ("Bharat Petroleum", "BPCL.NS", "Energy"),
    ("Indian Bank", "INDIANBANK.NS", "Banking"),
    ("UCO Bank", "UCOBANK.NS", "Banking"),
    ("Bandhan Bank", "BANDHANBNK.NS", "Banking"),
    ("IDFC First Bank", "IDFCFIRSTB.NS", "Banking"),
    ("Punjab National Bank", "PNB.NS", "Banking"),
    ("Indian Railway Finance", "IRFC.NS", "Finance"),
    ("Shriram Finance", "SHRIRAMFIN.NS", "Finance"),
    ("AU Small Finance Bank", "AUBANK.NS", "Banking"),
    ("Bajaj Housing Finance", "BAJAJHLDNG.NS", "Finance"),
    ("Cholamandalam Investment", "CHOLAFIN.NS", "Finance"),
    ("L&T Finance Holdings", "LTFH.NS", "Finance"),
    ("Sundaram Finance", "SUNDARMFIN.NS", "Finance"),
    ("Muthoot Finance", "MUTHOOTFIN.NS", "Finance"),
    ("Home First Finance", "HOMEFIRST.NS", "Finance"),
    ("Poonawalla Fincorp", "POONAWALLA.NS", "Finance"),
    ("Avenue Supermarts", "DMART.NS", "Retail"),
    ("Trent", "TRENT.NS", "Retail"),
    ("Sapphire Foods", "SAPPHIRE.NS", "Food"),
    ("Eicher Motors", "EICHERMOT.NS", "Automobile"),
    ("Bajaj Auto", "BAJAJ-AUTO.NS", "Automobile"),
    ("TVS Motor", "TVSMOTOR.NS", "Automobile"),
    ("Apollo Tyres", "APOLLOTYRE.NS", "Tyres"),
    ("MRF", "MRF.NS", "Tyres"),
    ("Balkrishna Industries", "BALKRISIND.NS", "Tyres"),
    ("SRF", "SRF.NS", "Chemicals"),
    ("Aarti Drugs", "AARTIDRUGS.NS", "Pharma"),
    ("Gland Pharma", "GLAND.NS", "Pharma"),
    ("Mankind Pharma", "MANKIND.NS", "Pharma"),
    ("The Ramco Cements", "RAMCOCEM.NS", "Cement"),
    ("Dalmia Bharat", "DALBHARAT.NS", "Cement"),
    ("AIA Engineering", "AIAENG.NS", "Engineering"),
    ("Aegis Logistics", "AEGISLOG.NS", "Logistics"),
    ("Mphasis", "MPHASIS.NS", "IT"),
    ("Wipro", "WIPRO.NS", "IT"),
    ("HCL Tech", "HCLTECH.NS", "IT"),
    ("Tech Mahindra", "TECHM.NS", "IT"),
    ("LTI Mindtree", "LTIM.NS", "IT"),
    ("Coforge", "COFORGE.NS", "IT"),
    ("Jubilant FoodWorks", "JUBLFOOD.NS", "Food"),
    ("Bharat Forge", "BHARATFORG.NS", "Auto Components"),
    ("Minda Industries", "MINDAIND.NS", "Auto Components"),
]

results = {}
for name, ticker, sector in candidates:
    try:
        data = yf.Ticker(ticker).history(period='2d')
        if data is not None and not data.empty:
            results[name] = {'NSE': ticker, 'BSE': '999999999.BO', 'sector': sector}
    except Exception:
        pass
    time.sleep(0.15)
    if len(results) >= 500:
        break

os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
with open(OUTPUT_FILE, 'w', encoding='utf-8') as fh:
    json.dump(results, fh, indent=2, ensure_ascii=False)

print(f'found={len(results)}')
print(list(results)[:10])
